### ISSUE TITLE
--filters \.g.dart is also filtering non-generated files whose name ends with the letter g

### ISSUE THREAD

**Issue by babbage** [mrverdant13/coverde#51]
Command:
`melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart`

Example filter output:
```
modulename:
<lib/src/buttons/modulename_rating.dart> coverage data ignored.
<lib/src/dialogs/modulename_general_dialog.dart> coverage data ignored.
<lib/src/other_ui_widgets/modulename_tag.dart> coverage data ignored.
modulename: SUCCESS
```

Another example, same run, different module:
```
othermodule:
<lib/src/models/meeting.dart> coverage data ignored.
<lib/src/models/meeting.g.dart> coverage data ignored.
<lib/src/models/service_call_info.g.dart> coverage data ignored.
othermodule: SUCCESS
```

It appears the leading \. is being ignored in this filtering for some reason?

**Comment by mrverdant13** [comment]
Hello, @babbage ! 👋🏼 
Thanks for the report

These days I am working on a refactor and potential performance improvements, so I'll take a look

In the meantime, could you please try with the surrounding quotes for the deferred melos command?
```sh
melos exec -c 1 --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart"
```

**Comment by mrverdant13** [comment]
Hey, @babbage
I just noticed the issue here.
The tool is actually filtering the data as expected.

First, it is important to note that **the patterns provided in the `--filters` option are transformed to `RegExp` objects**.

As a result, the `--filters \.g\.dart` setup would be transformed to `RegExp('.g.dart')`, which can be explained as:

- **`.`**: Matches any character except line breaks.
- **`g`**: Matches a `g` character. Case-sensitive.
- **`.`**: Matches any character except line breaks.
- **`dart`**: Matches the `dart` character sequence. Case-sensitive.

So, to achieve what you are looking for, you need to use a _raw string_.
In Dart, the raw strings are formed by prefixing the string literal with the `r` character.
In the console/terminal, to pass a raw string as a CLI option, you need to use surrounding quotes.
Then, you need to use the `--filters '\.g\.dart'` setup, that would be transformed to `RegExp(r'\.g\.dart')`, which can be explained as:

- **Escaped `.`**: Matches a `.` character.
- **`g`**: Matches a `g` character. Case-sensitive.
- **Escaped `.`**: Matches a `.` character.
- **`dart`**: Matches the `dart` character sequence. Case-sensitive.
That, in short, means that the entire `.g.dart` character case-sensitive sequence.

I hope that helps.
I will add a FAQ section in the docs describing this, since I believe that users are not aware of these caveats.
Besides that, I will update the tests to include this missing case.

Thanks again for opening the issue!
Cheers!
