### ISSUE TITLE
Need a feature to exclude some files

### ISSUE THREAD

**Issue by aguung** [mrverdant13/coverde#76]
This library really helps me to generate reports. Maybe you can add a feature/command to exclude some build_runner files with the pattern g.dart/freezed.dart

Thank You

**Comment by mrverdant13** [comment]
Hey, @aguung 👋🏼 !

The feature you just described already exists.
Have you checked the [`coverde filter` command](https://github.com/mrverdant13/coverde#coverde-filter)?

**Comment by aguung** [comment]
From my code there are build results from parts g.dart and frozen.dart . I have tried running this command but g.dart is still detected in the report results

**Comment by mrverdant13** [comment]
I see
That is the expected behaviour

The `coverde filter` command uses `coverage/lcov.info` as input and `coverage/filtered.lcov.info` as output. Those are the default, but they can be specified by the `--input`/`-i` and `--output`/`-o` options.
This is described in the [`coverde filter` command docs](https://pub.dev/packages/coverde#coverde-filter).

In your case, the updated filtered trace file would be the `coverage/filtered.lcov.info` file, which is the one that you may use for the report generation with the `--input`/`-i` option for the [`coverde report` command](https://pub.dev/packages/coverde#coverde-report).

Hope it helps! 🖖🏼

**Comment by aguung** [comment]
OK, thanks, it works. Sorry for not reading the document carefully.
